# Generated by Django 2.0.4 on 2018-04-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='transcription',
            field=models.TextField(blank=True),
        ),
    ]
