# Generated by Django 2.0.4 on 2018-04-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0003_auto_20180423_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTranscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.TextField()),
                ('author', models.CharField(blank=True, max_length=50)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcribe.Text')),
            ],
        ),
    ]
